### PR TITLE
Github-actions fixes

### PR DESCRIPTION
**Pull request by Thieum**
Attempt to fix everything that is flagged by vcpkg github action.

### CODE REVIEW

**Comment by cenit** [comment]
thanks, but rtabmap is bsd right?

**Comment by cenit** [comment]
i am so sorry in this period i am extremely busy, unable to fix the PR. Thanks again for your help

**Comment by cenit** [comment]
also dbow3 is BDS-3-clause

i fixed them, thanks again

**Comment by Thieum** [comment]
> i am so sorry in this period i am extremely busy, unable to fix the PR. Thanks again for your help

no worries, thanks to you, some of those PR became a marathon easily!

**Pull request merged**
